"""Jobs for running the workflow."""

from jobflow import job, Flow, Response
from dataclasses import field
from autoplex.auto.GenMLFF.rss import RandomizedStructureMaker
from autoplex.auto.GenMLFF.labelling import MLIPStaticLabelling
from autoplex.auto.GenMLFF.dataset import DatasetMaker

@job
def initial_iteration(
    name: str = "initial_iteration",
    rss_params: dict = field(default_factory=dict),
    mlip_params: dict = field(default_factory=dict),
    dataset_params: dict = field(default_factory=dict),
):
    """
    Start the initial iteration of the workflow.
    This function initializes the RandomizedStructureMaker and MLIPStaticLabelling.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the RandomizedStructureMaker.
    """

    #Define joblist
    joblist = []

    #Initialize the RandomizedStructureMaker with the provided parameters
    rss_job = RSS(**rss_params)
    joblist.append(rss_job)

    # Initialize the MLIPStaticLabelling with the provided parameters and
    # Perform MLIP static labelling on the structures generated by the RSS job
    mlip_job = MLscf(**mlip_params, structure_paths=rss_job.output)
    joblist.append(mlip_job)

    # Initialize the DatasetEnsembler with the provided parameters and
    # Perform dataset ensemble split on the labelled structures generated by the MLIP job
    dataset_job = dataset_ensembler(**dataset_params, labeled_data_file=mlip_job.output)
    joblist.append(dataset_job)

    #Create a Flow object to manage the jobs
    flow = Flow(jobs=joblist, name=name)

    return Response(
        replace=flow,
        output={
            "rss_output": rss_job.output,
            "mlip_output": mlip_job.output,
            "dataset_output": dataset_job.output,
        })


@job
def RSS(
    name: str = "random_search_structure_job",
    tag: str = None,
    output_file_name: str = "random_structs.extxyz",
    generated_struct_numbers: list[int] | None = None,
    buildcell_options: list[dict] | None = None,
    cell_seed_path: str | None = None,
    fragment_file: str | None = None,
    fragment_numbers: list[str] | None = None,
    remove_tmp_files: bool = True,
    num_processes: int = 1,
):
    """
    Initialize the RandomizedStructureMaker with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the RandomizedStructureMaker.
    """
    #Parameters for RandomizedStructureMaker
    rss_params = {
        "name": name,
        "tag": tag,
        "output_file_name": output_file_name,
        "generated_struct_numbers": generated_struct_numbers,
        "buildcell_options": buildcell_options,
        "cell_seed_path": cell_seed_path,
        "fragment_file": fragment_file,
        "fragment_numbers": fragment_numbers,
        "remove_tmp_files": remove_tmp_files,
        "num_processes": num_processes,
    }

    # Execute randomized structure generation
    # and return the paths to the generated structures
    randomized_structures_paths = RandomizedStructureMaker(**rss_params).make()

    return randomized_structures_paths


@job
def MLscf(
    name: str = "do_mlip_static_labelling",
    mlip_type: str | None = None,
    mlip_kwargs: dict | None = None,
    structure_paths: list[str] | None = None,
    structure_types: list[str] | None = None,
    isolated_atom: bool = False,
    isolated_species: list[str] | None = None,
    isolatedatom_box: list[float] | None = None,
    dimer: bool = False,
    dimer_pairs: list[tuple[str]] | None = None,
    dimer_range: list[float] | None = None,
    dimer_num: int = 21,
    dimer_box: list[float] | None = None,
):
    """
    Initialize the MLIPStaticLabelling with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the MLIPStaticLabelling.
    """
    #Parameters for MLIPStaticLabelling
    mlip_params = {
        "name": name,
        "mlip_type": mlip_type,
        "mlip_kwargs": mlip_kwargs,    
        "structure_paths": structure_paths,
        "structure_types": structure_types,    
        "isolated_atom": isolated_atom,
        "isolated_species": isolated_species,
        "isolatedatom_box": isolatedatom_box,
        "dimer": dimer,
        "dimer_pairs": dimer_pairs,
        "dimer_range": dimer_range,
        "dimer_num": dimer_num,
        "dimer_box": dimer_box,
    }

    # Execute MLIP static labelling
    # and return the paths to the labelled structures
    labelled_structures_path = MLIPStaticLabelling(**mlip_params).make()

    return labelled_structures_path

@job
def dataset_ensembler(
    name: str = "do_ensemble_split_dataset",
    labeled_data_file: str | None = None,
    num_models: int = 1,
    test_ratio: float = 0.1,
    distill_force_max: float | None = None,
    force_label: str = "REF_forces",
    energy_label: str = "REF_energy",
    output_file_name: str = "unique_dataset.extxyz",
    pre_database_dir: str | None = None,
    isolated_atom_energies: dict | None = None
):
    """
    Initialize the DatasetEnsembler with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the DatasetEnsembler.
    """
    #Check if the labeled_data_file is provided
    if labeled_data_file is None:
        raise ValueError("labeled_data_file must be provided.")
    
    #Collect parameters for DatasetMaker
    dataset_maker_params = {
        "labeled_data_file": labeled_data_file,
        "num_models": num_models,
        "test_ratio": test_ratio,
        "distill_force_max": distill_force_max,
        "force_label": force_label,
        "energy_label": energy_label,
        "output_file_name": output_file_name,
        "pre_database_dir": pre_database_dir,
        "isolated_atom_energies": isolated_atom_energies
    }

    # Execute dataset ensembling
    # and return the path to the ensembled dataset
    ensembled_dataset_paths = DatasetMaker(**dataset_maker_params).make()

    return ensembled_dataset_paths