"""Jobs for running the workflow."""

from dataclasses import field
from jobflow import job, Flow, Response
from autoplex.auto.GenMLFF.rss import RandomizedStructureMaker
from autoplex.auto.GenMLFF.labelling import MLIPStaticLabelling, QEstaticLabelling
from autoplex.auto.GenMLFF.dataset import DatasetMaker
from autoplex.auto.GenMLFF.training import MLIPEnsembleMaker
from autoplex.auto.GenMLFF.sampling import EnsembleEvaluatorMaker


@job
def initial_iteration(
    name: str = "initial_iteration",
    rss_params: dict = field(default_factory=dict),
    mlip_params: dict = field(default_factory=dict),
    dataset_params: dict = field(default_factory=dict),
    train_params: dict = field(default_factory=dict),
):
    """
    Start the initial iteration of the workflow.
    This function initializes the RandomizedStructureMaker and MLIPStaticLabelling.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the RandomizedStructureMaker.
    """

    #Define joblist
    joblist = []

    #Initialize the RandomizedStructureMaker with the provided parameters
    rss_job = RSS(**rss_params)
    joblist.append(rss_job)

    # Initialize the MLIPStaticLabelling with the provided parameters and
    # Perform MLIP static labelling on the structures generated by the RSS job
    mlip_job = MLscf(**mlip_params, structure_paths=rss_job.output)
    joblist.append(mlip_job)

    # Initialize the DatasetEnsembler with the provided parameters and
    # Perform dataset ensemble split on the labelled structures generated by the MLIP job
    dataset_job = dataset_ensembler(**dataset_params, labeled_data_file=mlip_job.output)
    joblist.append(dataset_job)

    # Initialize the MLIPEnsembleMaker with the provided parameters and
    # Perform MLIP ensemble fitting on the ensembled dataset generated by the DatasetEnsembler job
    mlip_ensemble_job = fit_mlip_ensemble(**train_params, dataset_path=dataset_job.output)
    joblist.append(mlip_ensemble_job)

    #Create a Flow object to manage the jobs
    flow = Flow(jobs=joblist, name=name)

    return Response(
        replace=flow,
        output={
            "rss_output": rss_job.output,
            "mlip_output": mlip_job.output,
            "dataset_output": dataset_job.output,
            "training_output": mlip_ensemble_job.output,
        })


@job
def standard_iteration(
    name: str = "standard_iteration",
    rss_params: dict = field(default_factory=dict),
    sample_params: dict = field(default_factory=dict),
    mlip_params: dict = field(default_factory=dict),
    dataset_params: dict = field(default_factory=dict),
    train_params: dict = field(default_factory=dict),
):
    """
    Start the standard iteration of the workflow.
    This function initializes the MLIPEnsembleEvaluator.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the MLIPEnsembleEvaluator.
    """

    #Define joblist
    joblist = []

    # Initialize the MLIPEnsembleEvaluator with the provided parameters
    mlip_evaluator_job = evaluate_mlip_ensemble(**mlip_params)
    joblist.append(mlip_evaluator_job)

    # Create a Flow object to manage the jobs
    flow = Flow(jobs=joblist, name=name)

    return Response(
        replace=flow,
        output={
            "mlip_evaluator_output": mlip_evaluator_job.output,
        })


@job
def RSS(
    name: str = "random_search_structure_job",
    tag: str = None,
    output_file_name: str = "random_structs.extxyz",
    generated_struct_numbers: list[int] | None = None,
    buildcell_options: list[dict] | None = None,
    cell_seed_path: str | None = None,
    fragment_file: str | None = None,
    fragment_numbers: list[str] | None = None,
    remove_tmp_files: bool = True,
    num_processes: int = 1,
):
    """
    Initialize the RandomizedStructureMaker with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the RandomizedStructureMaker.
    """
    #Parameters for RandomizedStructureMaker
    rss_params = {
        "name": name,
        "tag": tag,
        "output_file_name": output_file_name,
        "generated_struct_numbers": generated_struct_numbers,
        "buildcell_options": buildcell_options,
        "cell_seed_path": cell_seed_path,
        "fragment_file": fragment_file,
        "fragment_numbers": fragment_numbers,
        "remove_tmp_files": remove_tmp_files,
        "num_processes": num_processes,
    }

    # Execute randomized structure generation
    # and return the paths to the generated structures
    randomized_structures_paths = RandomizedStructureMaker(**rss_params).make()

    return randomized_structures_paths


@job
def MLscf(
    name: str = "do_mlip_static_labelling",
    mlip_type: str | None = None,
    mlip_kwargs: dict | None = None,
    structure_paths: list[str] | None = None,
    structure_types: list[str] | None = None,
    isolated_atom: bool = False,
    isolated_species: list[str] | None = None,
    isolatedatom_box: list[float] | None = None,
    dimer: bool = False,
    dimer_pairs: list[tuple[str]] | None = None,
    dimer_range: list[float] | None = None,
    dimer_num: int = 21,
    dimer_box: list[float] | None = None,
):
    """
    Initialize the MLIPStaticLabelling with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the MLIPStaticLabelling.
    """
    #Parameters for MLIPStaticLabelling
    mlip_params = {
        "name": name,
        "mlip_type": mlip_type,
        "mlip_kwargs": mlip_kwargs,    
        "structure_paths": structure_paths,
        "structure_types": structure_types,    
        "isolated_atom": isolated_atom,
        "isolated_species": isolated_species,
        "isolatedatom_box": isolatedatom_box,
        "dimer": dimer,
        "dimer_pairs": dimer_pairs,
        "dimer_range": dimer_range,
        "dimer_num": dimer_num,
        "dimer_box": dimer_box,
    }

    # Execute MLIP static labelling
    # and return the paths to the labelled structures
    labelled_structures_path = MLIPStaticLabelling(**mlip_params).make()

    return labelled_structures_path


@job
def QEscf(
    name: str = "do_qe_static_labelling",
    qe_run_cmd: str = "mpirun -np 1 pw.x",
    num_qe_workers: int | None = 1, #Number of workers to use for the calculations. If None setp up 1 worker per scf
    fname_pwi_template: str | None = None, #Path to file containing the template QE input
    fname_structures: str | None = None, #Path to ASE-readible file containing the structures to be computed
):
    """
    Initialize the QEScfLabelling with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the QEScfLabelling.
    """
    #Parameters for QEScfLabelling
    qe_params = {
        "name": name,
        "qe_run_cmd": qe_run_cmd,
        "num_qe_workers": num_qe_workers,
        "fname_pwi_template": fname_pwi_template,
        "fname_structures": fname_structures,
    }

    # Execute QE static labelling
    # return a list containing (list[success], list[pwo], list[outdir]) for each worker
    output_per_worker = QEstaticLabelling(**qe_params).make()

    return output_per_worker

@job
def dataset_ensembler(
    name: str = "do_ensemble_split_dataset",
    labeled_output: str | list | None = None,
    num_models: int = 1,
    test_ratio: float = 0.1,
    distill_force_max: float | None = None,
    force_label: str = "REF_forces",
    energy_label: str = "REF_energy",
    output_file_name: str = "unique_dataset.extxyz",
    pre_database_dir: str | None = None,
    isolated_atom_energies: dict | None = None
):
    """
    Initialize the DatasetEnsembler with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the DatasetEnsembler.
    """
    #Check if the labeled_data_file is provided
    if labeled_output is None:
        raise ValueError("labeled_data_file must be provided.")
    
    #Collect parameters for DatasetMaker
    dataset_maker_params = {
        "labeled_output": labeled_output,
        "num_models": num_models,
        "test_ratio": test_ratio,
        "distill_force_max": distill_force_max,
        "force_label": force_label,
        "energy_label": energy_label,
        "output_file_name": output_file_name,
        "pre_database_dir": pre_database_dir,
        "isolated_atom_energies": isolated_atom_energies
    }

    # Execute dataset ensembling
    # and return the path to the ensembled dataset
    ensembled_dataset_paths = DatasetMaker(**dataset_maker_params).make()

    return ensembled_dataset_paths


@job
def fit_mlip_ensemble(
    name: str = "do_mlip_ensemble_fitting",
    dataset_path: str | None = None,
    mlip_type: str | None = None,
    mlip_train_kwargs: dict = field(default_factory=dict),
    num_models: int = 1,
    remove_model_datasets: bool = True,
):
    """
    Initialize the MLIPEnsembleMaker with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the MLIPEnsembleMaker.
    """
    #Check if the dataset_path is provided
    if dataset_path is None:
        raise ValueError("dataset_path must be provided.")
    
    #Collect parameters for MLIPEnsembleMaker
    mlip_ensemble_params = {
        "dataset_path": dataset_path,
        "mlip_type": mlip_type,
        "mlip_train_kwargs": mlip_train_kwargs,
        "num_models": num_models,
        "remove_model_datasets": remove_model_datasets,
    }

    # Execute MLIP ensemble fitting: return {"mlip_paths": [paths], "train_errors": [floats], "test_errors": [floats], "converges": [bools]}
    fitted_model_paths = MLIPEnsembleMaker(**mlip_ensemble_params).make()

    return fitted_model_paths


@job
def evaluate_mlip_ensemble(
    name: str = "do_relaxation_and_sampling",
    mlip_type: str | None = None,
    mlip_paths: list[str] | None = None,
    mlip_errors: list[float] | None = None,
    mlip_kwargs: dict | None = None,
    structure_paths: list[str] | None = None,
    pre_trained_model: str | None = None,
    pre_trained_kwargs: dict | None = None,
):
    """
    Initialize the MLIPEnsembleEvaluator with the provided parameters.

    Parameters
    ----------
    kwargs: dict
        Dictionary containing the parameters for the MLIPEnsembleEvaluator.
    """
    #Check if the mlip_paths and structure_paths are provided
    if mlip_paths is None or structure_paths is None:
        raise ValueError("mlip_paths and structure_paths must be provided.")
    
    #Collect parameters for MLIPEnsembleEvaluator
    ensemble_evaluator_params = {
        "mlip_type": mlip_type,
        "mlip_paths": mlip_paths,
        "mlip_errors": mlip_errors,
        "mlip_kwargs": mlip_kwargs,
        "structure_paths": structure_paths,
        "pre_trained_model": pre_trained_model,
        "pre_trained_kwargs": pre_trained_kwargs,
    }

    # Execute relaxation of the generated structures
    # Perform the ensemble evaluation and sample the most "problematic" structures
    # Return the paths to the sampled structures
    evaluated_structures_path = EnsembleEvaluatorMaker(**ensemble_evaluator_params).make()

    return evaluated_structures_path